In [124]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import MissingIndicator, SimpleImputer 

In [125]:
df = pd.read_csv('train_titanic.csv', usecols=['Fare', 'Age','Survived'])

In [126]:
df.head()

Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [127]:
X = df.drop(columns=['Survived'])
Y = df['Survived']

In [128]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, train_size=0.25)

In [129]:
X_train.head()

Age     Fare
590  35.0   7.1250
164   1.0  39.6875
149  42.0  13.0000
363  35.0   7.0500
791  16.0  26.0000

In [130]:
si = SimpleImputer()
X_train_trf = si.fit_transform(X_train)
X_test_trf = si.transform(X_test)

In [131]:
X_train_trf

array([[3.50000000e+01, 7.12500000e+00],
       [1.00000000e+00, 3.96875000e+01],
       [4.20000000e+01, 1.30000000e+01],
       [3.50000000e+01, 7.05000000e+00],
       [1.60000000e+01, 2.60000000e+01],
       [2.90000000e+01, 7.87500000e+00],
       [2.80000000e+01, 7.92500000e+00],
       [2.92876836e+01, 3.00000000e+01],
       [3.70000000e+01, 2.97000000e+01],
       [2.92876836e+01, 7.75000000e+00],
       [1.80000000e+01, 7.79580000e+00],
       [2.20000000e+01, 7.25000000e+00],
       [2.92876836e+01, 8.05000000e+00],
       [2.92876836e+01, 2.32500000e+01],
       [2.00000000e+01, 9.22500000e+00],
       [2.92876836e+01, 5.64958000e+01],
       [2.92876836e+01, 7.89580000e+00],
       [5.70000000e+01, 1.05000000e+01],
       [2.50000000e+01, 9.10792000e+01],
       [1.90000000e+01, 2.62833000e+01],
       [2.30000000e+01, 7.89580000e+00],
       [3.80000000e+01, 1.30000000e+01],
       [4.00000000e+01, 2.77208000e+01],
       [8.00000000e+00, 2.62500000e+01],
       [1.900000

In [132]:
# Model Training

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

lr = LogisticRegression()

lr.fit(X_train_trf, y_train)

y_pred = lr.predict(X_test_trf)

accuracy_score(y_test, y_pred)



0.6591928251121076

In [133]:
mi = MissingIndicator()

mi.fit(X_train)

MissingIndicator()

In [134]:
mi.features_

array([0], dtype=int64)

In [135]:
X_train_missing = mi.transform(X_train)

In [136]:
X_train_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [

In [137]:
X_test_missing = mi.transform(X_test)

In [138]:
X_train['Age_NA'] = X_train_missing

In [139]:
X_test['Age_NA'] = X_test_missing

In [140]:
X_train

Age     Fare  Age_NA
590  35.0   7.1250   False
164   1.0  39.6875   False
149  42.0  13.0000   False
363  35.0   7.0500   False
791  16.0  26.0000   False
..    ...      ...     ...
722  34.0  13.0000   False
846   NaN  69.5500    True
569  32.0   7.8542   False
486  35.0  90.0000   False
804  27.0   6.9750   False

[222 rows x 3 columns]

In [141]:
X_test

Age      Fare  Age_NA
498  25.00  151.5500   False
639    NaN   16.1000    True
765  51.00   77.9583   False
32     NaN    7.7500    True
755   0.67   14.5000   False
..     ...       ...     ...
60   22.00    7.2292   False
882  22.00   10.5167   False
6    54.00   51.8625   False
24    8.00   21.0750   False
129  45.00    6.9750   False

[669 rows x 3 columns]

In [145]:
si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [146]:
from sklearn.linear_model import LogisticRegression

clf  = LogisticRegression()
clf.fit(X_train_trf2, y_train)

y_pred = clf.predict(X_test_trf2)

accuracy_score(y_test, y_pred)

0.656203288490284

In [147]:
si = SimpleImputer(add_indicator=True)
X_train = si.fit_transform(X_train)
X_test = si.transform(X_test)

In [149]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf2,y_train)

y_pred = clf.predict(X_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)*100

65.6203288490284