In [18]:
import pickle
import numpy as np

In [19]:
ohe_sex = pickle.load(open('model/ohe_sex.pkl', 'rb'))
ohe_embarked = pickle.load(open('model/ohe_embaked.pkl', 'rb'))
clf = pickle.load(open('model/clf.pkl', 'rb'))

Input - Pclass, Gender, Age, Sibsip, Parch, Fare, Embarked

In [20]:
test_input = np.array([2, 'male', 31.0, 0, 0 , 10.5, 'S'], dtype = object).reshape(1, 7)

In [21]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [22]:
test_input_sex  = ohe_sex.transform(test_input[:,1].reshape(1,1))

c:\Users\91741\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [23]:
test_input_sex

array([[0., 1.]])

In [24]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [25]:
test_input_embarked

array([[0., 0., 1.]])

In [26]:
test_input_age = test_input[:,2].reshape(1,1)

In [27]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]], test_input_age,test_input_embarked, test_input_sex), axis= 1)

In [28]:
test_input_transformed.shape

(1, 10)

In [29]:
clf.predict(test_input_transformed)

array([0], dtype=int64)